spring.application.name=crm

spring.config.import=classpath:secrets.properties

# DataSource Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql = true
spring.data.jpa.repositories.enabled=true
spring.jpa.database=mysql
server.error.include-message=always

#Jwt related configurations
#secret key
com.aefstathiou.jwt-secret=${JWT_SECRET}
#access token expiration 1 day
com.aefstathiou.jwt-access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
#refresh token expiration 1 week
com.aefstathiou.jwt-refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}
